image: ruby:2.2.3
git:
  path: github.com/hushaoping/service3
script:
  - echo "build commands"
  - .shipped/build
  - .shipped/test
clone:
  path: github.com/hushaoping/service3
build:
  image: ruby:2.2.3
  commands:
    - echo "build commands"
    - .shipped/build
    - .shipped/test
publish:
  docker:
    file: ./Dockerfile
    insecure: true
    username: $$docker_user
    password: $$docker_key
    registry: $$docker_registry
    repo: $$docker_repo
    email: $$docker_user_email
    tag: $$COMMIT
    
